export { createSupabaseClient, getSupabaseUrl } from "./client.js";
export {
  signInWithGoogle,
  getGoogleOAuthUrl,
  exchangeCodeForSession,
  signInWithDiscord,
  signInWithEmailOtp,
  sendMagicLink,
  verifyEmailOtp,
  signOut,
  getSession,
  onAuthStateChange,
} from "./auth.js";
export type { Session, User, AuthChangeEvent } from "@supabase/supabase-js";
export {
  openBoosterPack,
  getCollection,
  getCharacter,
  getActiveParty,
  setActiveParty,
  getDailyPacksRemaining,
  getGachaConfig,
  updateGachaConfig,
  generateTestCharacter,
  generateCharacterText,
  generateCharacterImage,
  assignCharacterVoice,
  previewVoice,
  updateCharacter,
  getAllCharacters,
  deleteCharacter,
  deleteAllCharacters,
  purgeCharacterMedia,
  purgeAllDeletedCharacters,
  getDeletedCharacters,
  toggleCharacterActive,
  setDefaultCharacter,
  syncFishVoices,
  getFishVoices,
  generativeTts,
  getCharacterTemplates,
  rollTokenPools,
  buildDirective,
  weightedPick,
} from "./gacha.js";
export type { FishVoice, TokenPool, TokenPools, TokenPoolEntry, TokenRoll } from "./gacha.js";
