-- Seed default token pools into gacha_config for weighted character diversity
UPDATE gacha_config
SET config = config || '{
  "tokenPools": {
    "gender": {
      "label": "Gender",
      "description": "Character gender identity",
      "entries": [
        {"value": "male", "weight": 40},
        {"value": "female", "weight": 40},
        {"value": "non-binary", "weight": 15},
        {"value": "ambiguous", "weight": 5}
      ]
    },
    "species": {
      "label": "Species",
      "description": "Character species or race",
      "entries": [
        {"value": "human", "weight": 30},
        {"value": "robot", "weight": 10},
        {"value": "alien", "weight": 8},
        {"value": "elf", "weight": 7},
        {"value": "catfolk", "weight": 6},
        {"value": "dragon-kin", "weight": 5},
        {"value": "dwarf", "weight": 5},
        {"value": "orc", "weight": 4},
        {"value": "undead", "weight": 4},
        {"value": "slime", "weight": 3},
        {"value": "ghost", "weight": 3},
        {"value": "fairy", "weight": 3},
        {"value": "demon", "weight": 3},
        {"value": "angel", "weight": 3},
        {"value": "goblin", "weight": 2},
        {"value": "werewolf", "weight": 2},
        {"value": "vampire", "weight": 2},
        {"value": "merfolk", "weight": 2},
        {"value": "centaur", "weight": 1},
        {"value": "treant", "weight": 1},
        {"value": "phoenix", "weight": 1},
        {"value": "minotaur", "weight": 1},
        {"value": "lizardfolk", "weight": 1},
        {"value": "mushroom person", "weight": 1}
      ]
    },
    "ethnicity": {
      "label": "Ethnicity",
      "description": "Cultural/ethnic background (only when species is human)",
      "entries": [
        {"value": "East Asian", "weight": 10},
        {"value": "South Asian", "weight": 8},
        {"value": "Southeast Asian", "weight": 6},
        {"value": "West African", "weight": 8},
        {"value": "East African", "weight": 5},
        {"value": "North African", "weight": 4},
        {"value": "Western European", "weight": 10},
        {"value": "Eastern European", "weight": 6},
        {"value": "Northern European", "weight": 5},
        {"value": "Southern European", "weight": 5},
        {"value": "Latin American", "weight": 8},
        {"value": "Caribbean", "weight": 4},
        {"value": "Middle Eastern", "weight": 6},
        {"value": "Central Asian", "weight": 3},
        {"value": "Pacific Islander", "weight": 3},
        {"value": "Indigenous American", "weight": 4},
        {"value": "Mixed heritage", "weight": 8},
        {"value": "Ambiguous", "weight": 5}
      ],
      "conditionalOn": {"pool": "species", "values": ["human"]}
    },
    "ageRange": {
      "label": "Age Range",
      "description": "Character apparent age bracket",
      "entries": [
        {"value": "child", "weight": 5},
        {"value": "teenager", "weight": 10},
        {"value": "young adult", "weight": 30},
        {"value": "adult", "weight": 25},
        {"value": "middle-aged", "weight": 12},
        {"value": "elderly", "weight": 8},
        {"value": "ageless", "weight": 10}
      ]
    },
    "archetype": {
      "label": "Archetype",
      "description": "Character role or profession archetype",
      "entries": [
        {"value": "samurai", "weight": 5},
        {"value": "hacker", "weight": 5},
        {"value": "pirate captain", "weight": 5},
        {"value": "mad scientist", "weight": 5},
        {"value": "pro gamer", "weight": 6},
        {"value": "plague doctor", "weight": 4},
        {"value": "space trucker", "weight": 4},
        {"value": "street chef", "weight": 4},
        {"value": "bounty hunter", "weight": 5},
        {"value": "librarian", "weight": 3},
        {"value": "DJ", "weight": 4},
        {"value": "exorcist", "weight": 3},
        {"value": "mech pilot", "weight": 5},
        {"value": "detective", "weight": 4},
        {"value": "witch", "weight": 4},
        {"value": "bard", "weight": 4},
        {"value": "gladiator", "weight": 3},
        {"value": "ninja", "weight": 4},
        {"value": "alchemist", "weight": 3},
        {"value": "time traveler", "weight": 4},
        {"value": "necromancer", "weight": 3},
        {"value": "monk", "weight": 3},
        {"value": "smuggler", "weight": 3},
        {"value": "idol singer", "weight": 4},
        {"value": "wrestler", "weight": 3},
        {"value": "street racer", "weight": 3},
        {"value": "archaeologist", "weight": 3},
        {"value": "royal guard", "weight": 3},
        {"value": "fortune teller", "weight": 3},
        {"value": "war medic", "weight": 3},
        {"value": "thief", "weight": 3},
        {"value": "gunslinger", "weight": 4},
        {"value": "blacksmith", "weight": 3},
        {"value": "merchant", "weight": 3},
        {"value": "ranger", "weight": 3},
        {"value": "spy", "weight": 4},
        {"value": "summoner", "weight": 3},
        {"value": "paladin", "weight": 3},
        {"value": "berserker", "weight": 3},
        {"value": "engineer", "weight": 3},
        {"value": "shaman", "weight": 3},
        {"value": "assassin", "weight": 4},
        {"value": "clown", "weight": 2},
        {"value": "drill sergeant", "weight": 3},
        {"value": "bartender", "weight": 3},
        {"value": "astronaut", "weight": 3},
        {"value": "janitor", "weight": 2},
        {"value": "streamer", "weight": 5},
        {"value": "cryptid researcher", "weight": 2},
        {"value": "courier", "weight": 2},
        {"value": "vampire hunter", "weight": 3},
        {"value": "beast tamer", "weight": 3},
        {"value": "puppeteer", "weight": 2},
        {"value": "farmer", "weight": 2},
        {"value": "fisherman", "weight": 2},
        {"value": "dream walker", "weight": 3}
      ]
    },
    "personalityVibe": {
      "label": "Personality Vibe",
      "description": "Core personality energy or mood",
      "entries": [
        {"value": "cheerful", "weight": 8},
        {"value": "brooding", "weight": 6},
        {"value": "chaotic", "weight": 7},
        {"value": "sarcastic", "weight": 8},
        {"value": "deadpan", "weight": 6},
        {"value": "manic", "weight": 5},
        {"value": "nerdy", "weight": 7},
        {"value": "zen", "weight": 5},
        {"value": "dramatic", "weight": 6},
        {"value": "wholesome", "weight": 6},
        {"value": "cynical", "weight": 5},
        {"value": "flirty", "weight": 4},
        {"value": "mysterious", "weight": 5},
        {"value": "cocky", "weight": 5},
        {"value": "shy", "weight": 4},
        {"value": "goofy", "weight": 6},
        {"value": "grumpy", "weight": 5},
        {"value": "anxious", "weight": 4},
        {"value": "stoic", "weight": 5},
        {"value": "motherly", "weight": 3},
        {"value": "feral", "weight": 3},
        {"value": "chill", "weight": 6},
        {"value": "unhinged", "weight": 4},
        {"value": "noble", "weight": 4}
      ]
    },
    "definingTrait": {
      "label": "Defining Trait",
      "description": "A distinctive physical or behavioral quirk",
      "entries": [
        {"value": "eye patch", "weight": 4},
        {"value": "cybernetic arm", "weight": 5},
        {"value": "enormous mustache", "weight": 3},
        {"value": "always eating snacks", "weight": 5},
        {"value": "glowing eyes", "weight": 5},
        {"value": "wears a mask", "weight": 4},
        {"value": "speaks in third person", "weight": 3},
        {"value": "covered in tattoos", "weight": 4},
        {"value": "unnaturally tall", "weight": 3},
        {"value": "tiny and fierce", "weight": 4},
        {"value": "missing a tooth", "weight": 3},
        {"value": "always humming", "weight": 3},
        {"value": "carries a stuffed animal", "weight": 3},
        {"value": "scarred face", "weight": 4},
        {"value": "heterochromia", "weight": 4},
        {"value": "floating hair", "weight": 3},
        {"value": "mechanical voice", "weight": 3},
        {"value": "surrounded by butterflies", "weight": 2},
        {"value": "chain smoker", "weight": 3},
        {"value": "always cold", "weight": 3},
        {"value": "bioluminescent skin", "weight": 3},
        {"value": "extra arms", "weight": 2},
        {"value": "transparent body", "weight": 2},
        {"value": "wears only black", "weight": 4},
        {"value": "has a pet on their shoulder", "weight": 4},
        {"value": "narcoleptic", "weight": 2},
        {"value": "obsessed with collecting things", "weight": 4},
        {"value": "never stops smiling", "weight": 3},
        {"value": "perpetually exhausted", "weight": 4},
        {"value": "speaks with an accent", "weight": 3},
        {"value": "halo or horns", "weight": 3},
        {"value": "covered in bandages", "weight": 3},
        {"value": "wears oversized headphones", "weight": 4},
        {"value": "has a catchphrase for everything", "weight": 3},
        {"value": "leaves a trail of sparkles", "weight": 2}
      ]
    },
    "settingTheme": {
      "label": "Setting/Theme",
      "description": "The world or aesthetic the character comes from",
      "entries": [
        {"value": "cyberpunk megacity", "weight": 8},
        {"value": "medieval fantasy kingdom", "weight": 8},
        {"value": "deep space station", "weight": 6},
        {"value": "1980s arcade", "weight": 5},
        {"value": "underwater civilization", "weight": 4},
        {"value": "post-apocalyptic wasteland", "weight": 6},
        {"value": "steampunk Victorian", "weight": 5},
        {"value": "ancient mythology", "weight": 5},
        {"value": "haunted mansion", "weight": 4},
        {"value": "floating sky islands", "weight": 5},
        {"value": "neon-lit Tokyo streets", "weight": 6},
        {"value": "wild west frontier", "weight": 4},
        {"value": "enchanted forest", "weight": 4},
        {"value": "dystopian megacorp", "weight": 5},
        {"value": "pirate seas", "weight": 4},
        {"value": "arctic expedition", "weight": 3},
        {"value": "dream realm", "weight": 4},
        {"value": "underground fight club", "weight": 3},
        {"value": "magical academy", "weight": 5},
        {"value": "alien jungle planet", "weight": 4},
        {"value": "retro-futuristic 1950s", "weight": 3},
        {"value": "interdimensional bazaar", "weight": 3},
        {"value": "abandoned theme park", "weight": 3},
        {"value": "virtual reality MMO", "weight": 5}
      ]
    }
  }
}'::jsonb
WHERE id = 'default';
